apiVersion: apps/v1
kind: Pod
apiVersion: v1
metadata:
  name: echo-app
  labels:
    app: http-echo
spec:
  containers:
  - name: echo-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=echo"
    - "-listen=8080"
    ports:
    - containerPort: 8080
