apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-controller
  labels:
    app: ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-controller
  template:
    metadata:
      labels:
        app: ingress-controller
    spec:
      containers:
      - name: ingress-controller
        image: ingress-controller:mylatest
        ports:
        - containerPort: 80
---

# This is straight from https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: ingress-controller
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-controller
  namespace: default
subjects:
- kind: User
  name: ingress-controller
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ingress-controller
  apiGroup: rbac.authorization.k8s.io