apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: tcp

---

#apiVersion: networking.k8s.io/v1alpha4
#kind: Ingress
#metadata:
#  name: ingress-controller
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        backend:
#          serviceName: ingress-controller
#          servicePort: 80
